- name: Gather system info
  hosts: all
  gather_facts: yes

  tasks:
    - name: Show OS distribution info
      debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})"

    - name: Show total memory in MB
      debug:
        msg: "Total memory: {{ ansible_memtotal_mb }} MB"

    - name: Show number of CPU cores
      debug:
        msg: "CPU cores: {{ ansible_processor_cores }} per CPU, {{ ansible_processor_count }} CPUs, total {{ ansible_processor_vcpus }} vCPUs"

    - name: Show CPU model
      debug:
        msg: "{{ ansible_processor[1] }}"

    - name: Show all running processes (ps -ef)
      shell: ps -ef
      register: ps_output

    - name: Print process list
      debug:
        var: ps_output.stdout_lines
